/**
 * n-qubit statevector engine — pure TypeScript, zero dependencies.
 *
 * Implements the engine API contract of EXPLAINER-DESIGN.md §3: the
 * "hand-rolled TS statevector" recommended by the feasibility study
 * (docs/research/04-quantum-viz-education.md §4), with this repository's
 * Python emulator (quantum-linux/emulator/qcpu.py) as the cross-language
 * test ORACLE — identical circuits run on both engines must agree
 * amplitude-for-amplitude to 1e-9 (engine.test.ts + fixtures/oracle.json,
 * regenerated by fixtures/generate_fixtures.py).
 *
 * QUBIT ORDERING — little-endian, matching qcpu.py: bit `q` of the
 * basis-state index is qubit `q` (qubit 0 = least-significant bit).
 * Example (2 qubits): index 1 = binary `01` = qubit0:1, qubit1:0, i.e.
 * |01⟩ in the display order |q1 q0⟩. UI basis labels are therefore
 * ["|00⟩", "|01⟩", "|10⟩", "|11⟩"] with the RIGHTMOST character being
 * qubit 0 — `ketString` and `measureAll().bits` follow the same order.
 *
 * Unlike the single-qubit hero module (components/bloch/qubit.ts) this
 * engine does NOT pin global phase: the Python oracle applies raw
 * unitaries with no canonicalization, and matching it exactly is the
 * whole point. Gates are unitary ROTATIONS — the only non-unitary
 * operations here are `measureQubit` / `measureAll`.
 *
 * All functions are pure: every operation returns a new StateVector.
 * No classes. No external dependencies.
 */

import {
  type Complex,
  type Gate,
  complex,
  cAdd,
  cMul,
  cAbs,
  cPhase,
  H,
  X,
  Z,
  S,
} from "@/components/bloch/qubit";

export interface StateVector {
  nQubits: number;
  /** Basis-state amplitudes; amps.length === 2**nQubits (little-endian). */
  amps: Complex[];
}

const EPS = 1e-9;

/** Soft cap — the explainer never needs more than 3 qubits (GHZ tests). */
const MAX_QUBITS = 12;

/** Pauli-Y: [[0, −i], [i, 0]] (matches qcpu.py GATE_Y). */
const Y: Gate = [
  [complex(0), complex(0, -1)],
  [complex(0, 1), complex(0)],
];

/** T (π/8 gate, √S): [[1, 0], [0, e^{iπ/4}]] (matches qcpu.py GATE_T). */
const T: Gate = [
  [complex(1), complex(0)],
  [complex(0), complex(Math.cos(Math.PI / 4), Math.sin(Math.PI / 4))],
];

/** The single-qubit gate palette: H/X/Z/S from qubit.ts, Y/T local. */
export const GATES1: Record<"H" | "X" | "Y" | "Z" | "S" | "T", Gate> = {
  H,
  X,
  Y,
  Z,
  S,
  T,
};

function assertQubit(s: StateVector, q: number, what: string): void {
  if (!Number.isInteger(q) || q < 0 || q >= s.nQubits) {
    throw new RangeError(
      `${what}: qubit ${q} out of range 0..${s.nQubits - 1}`,
    );
  }
}

/** Fresh |0...0⟩ on `nQubits` qubits. */
export function zero(nQubits: number): StateVector {
  if (!Number.isInteger(nQubits) || nQubits < 1 || nQubits > MAX_QUBITS) {
    throw new RangeError(`zero: nQubits ${nQubits} out of range 1..${MAX_QUBITS}`);
  }
  const amps = Array.from({ length: 2 ** nQubits }, (_, i) =>
    complex(i === 0 ? 1 : 0),
  );
  return { nQubits, amps };
}

/**
 * Apply a 2×2 unitary to qubit `target`: for every index pair (i₀, i₁)
 * differing only in bit `target`, [a₀′, a₁′] = U·[a₀, a₁]. Same
 * convention as qcpu.py `apply_1q` (tensordot over the qubit's axis).
 */
export function applyGate1(
  s: StateVector,
  gate: Gate,
  target: number,
): StateVector {
  assertQubit(s, target, "applyGate1");
  const bit = 1 << target;
  const amps = s.amps.slice();
  for (let i0 = 0; i0 < amps.length; i0++) {
    if (i0 & bit) continue;
    const i1 = i0 | bit;
    const a0 = s.amps[i0];
    const a1 = s.amps[i1];
    amps[i0] = cAdd(cMul(gate[0][0], a0), cMul(gate[0][1], a1));
    amps[i1] = cAdd(cMul(gate[1][0], a0), cMul(gate[1][1], a1));
  }
  return { nQubits: s.nQubits, amps };
}

/**
 * CNOT: flip bit `target` of every basis state whose bit `control` is 1
 * (qcpu.py GATE_CNOT in |control target⟩ basis: |10⟩↔|11⟩).
 */
export function applyCNOT(
  s: StateVector,
  control: number,
  target: number,
): StateVector {
  assertQubit(s, control, "applyCNOT control");
  assertQubit(s, target, "applyCNOT target");
  if (control === target) {
    throw new RangeError(`applyCNOT: control === target (${control})`);
  }
  const cBit = 1 << control;
  const tBit = 1 << target;
  const amps = s.amps.slice();
  for (let i = 0; i < amps.length; i++) {
    if (i & cBit && !(i & tBit)) {
      const j = i | tBit;
      amps[i] = s.amps[j];
      amps[j] = s.amps[i];
    }
  }
  return { nQubits: s.nQubits, amps };
}

/**
 * CZ: negate the amplitude of every basis state with both bits set.
 * Symmetric in its arguments (qcpu.py GATE_CZ = diag(1,1,1,−1)).
 */
export function applyCZ(s: StateVector, a: number, b: number): StateVector {
  assertQubit(s, a, "applyCZ a");
  assertQubit(s, b, "applyCZ b");
  if (a === b) throw new RangeError(`applyCZ: a === b (${a})`);
  const mask = (1 << a) | (1 << b);
  const amps = s.amps.map((amp, i) =>
    (i & mask) === mask ? complex(-amp.re, -amp.im) : amp,
  );
  return { nQubits: s.nQubits, amps };
}

/** Born-rule probability |amp|² per basis state. */
export function probabilities(s: StateVector): number[] {
  return s.amps.map((a) => a.re * a.re + a.im * a.im);
}

/** Marginal probability of measuring qubit `q` as 0 / 1. */
export function probOfQubit(
  s: StateVector,
  q: number,
): { p0: number; p1: number } {
  assertQubit(s, q, "probOfQubit");
  const bit = 1 << q;
  let p0 = 0;
  let p1 = 0;
  for (let i = 0; i < s.amps.length; i++) {
    const a = s.amps[i];
    const p = a.re * a.re + a.im * a.im;
    if (i & bit) p1 += p;
    else p0 += p;
  }
  return { p0, p1 };
}

/**
 * Bloch vector of qubit `q`'s REDUCED density matrix ρ = Tr_others|ψ⟩⟨ψ|:
 * x = 2·Re ρ₀₁, y = −2·Im ρ₀₁, z = ρ₀₀ − ρ₁₁, r = |(x,y,z)|.
 *
 * Sign convention matches `blochAngles` in qubit.ts —
 * bloch = (sinθcosφ, sinθsinφ, cosθ): |0⟩ → z=+1, H|0⟩ → x=+1,
 * S·H|0⟩ → y=+1, each with r=1.
 *
 * r < 1 measures entanglement with the rest of the register — r = 0 for
 * either half of a Bell pair. That degeneration is the pedagogical point
 * (research doc §5: the Bloch sphere cannot show entanglement; its
 * breakdown IS the lesson).
 */
export function reducedBloch(
  s: StateVector,
  q: number,
): { x: number; y: number; z: number; r: number } {
  assertQubit(s, q, "reducedBloch");
  const bit = 1 << q;
  let z = 0;
  let re01 = 0;
  let im01 = 0;
  for (let i0 = 0; i0 < s.amps.length; i0++) {
    if (i0 & bit) continue;
    const a0 = s.amps[i0]; // qubit q = 0 component
    const a1 = s.amps[i0 | bit]; // qubit q = 1 component
    z += a0.re * a0.re + a0.im * a0.im - (a1.re * a1.re + a1.im * a1.im);
    // ρ₀₁ += a0 · conj(a1)
    re01 += a0.re * a1.re + a0.im * a1.im;
    im01 += a0.im * a1.re - a0.re * a1.im;
  }
  const x = 2 * re01;
  const y = -2 * im01;
  return { x, y, z, r: Math.hypot(x, y, z) };
}

/**
 * Concurrence of a 2-qubit PURE state: C = 2|a₀₀·a₁₁ − a₀₁·a₁₀|.
 * 0 for any product state, 1 for a Bell state (EXPLAINER-DESIGN §3).
 */
export function concurrence(s: StateVector): number {
  if (s.nQubits !== 2) {
    throw new RangeError(
      `concurrence: defined for 2-qubit pure states, got nQubits=${s.nQubits}`,
    );
  }
  // Little-endian: amps[1] = |01⟩ (qubit0=1), amps[2] = |10⟩ (qubit1=1).
  const d = cMul(s.amps[0], s.amps[3]); // a00·a11
  const e = cMul(s.amps[1], s.amps[2]); // a01·a10
  return Math.min(1, 2 * Math.hypot(d.re - e.re, d.im - e.im));
}

/**
 * Measure qubit `q` in the Z basis — THE only collapse in this engine.
 * Sampling convention matches qcpu.py `_sample_and_project`:
 * outcome = 1 iff rand() < P(1); the surviving branch is renormalized.
 */
export function measureQubit(
  s: StateVector,
  q: number,
  rand: () => number,
): { outcome: 0 | 1; collapsed: StateVector } {
  assertQubit(s, q, "measureQubit");
  const bit = 1 << q;
  const { p1 } = probOfQubit(s, q);
  const outcome: 0 | 1 = rand() < p1 ? 1 : 0;
  const norm = Math.sqrt(outcome === 1 ? p1 : Math.max(1 - p1, 0));
  const amps = s.amps.map((a, i) => {
    if (((i & bit) !== 0) !== (outcome === 1)) return complex(0);
    return norm > 0 ? complex(a.re / norm, a.im / norm) : complex(0);
  });
  return { outcome, collapsed: { nQubits: s.nQubits, amps } };
}

/**
 * Measure every qubit at once: one Born-rule draw over all 2ⁿ basis
 * states. `outcome` is the little-endian basis index; `bits` is the
 * display-order string |q_{n−1} … q₀⟩ (rightmost character = qubit 0).
 * The collapsed state keeps the measured amplitude's phase.
 */
export function measureAll(
  s: StateVector,
  rand: () => number,
): { outcome: number; bits: string; collapsed: StateVector } {
  const probs = probabilities(s);
  const r = rand();
  let outcome = probs.length - 1; // float-sum fallback: last state
  let acc = 0;
  for (let i = 0; i < probs.length; i++) {
    acc += probs[i];
    if (r < acc) {
      outcome = i;
      break;
    }
  }
  const a = s.amps[outcome];
  const mag = cAbs(a);
  const amps = s.amps.map((_, i) =>
    i === outcome
      ? mag > EPS
        ? complex(a.re / mag, a.im / mag)
        : complex(1)
      : complex(0),
  );
  return {
    outcome,
    bits: outcome.toString(2).padStart(s.nQubits, "0"),
    collapsed: { nQubits: s.nQubits, amps },
  };
}

/**
 * mulberry32 — tiny deterministic PRNG (32-bit seed → uniform [0, 1)).
 * Seeded measurement demos stay reproducible across reloads
 * (EXPLAINER-DESIGN §6, Ch5: fixed seed 0x5eed per mount).
 */
export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Display decomposition of one amplitude: magnitude + phase in degrees,
 * phaseDeg ∈ [0, 360). Phase-as-hue is the page's signature motif —
 * circle-notation fill is hsl(phaseDeg 80% 65%).
 */
export function ampDisplay(z: Complex): { mag: number; phaseDeg: number } {
  const mag = cAbs(z);
  let deg = (cPhase(z) * 180) / Math.PI;
  if (deg < 0) deg += 360;
  return { mag, phaseDeg: deg % 360 };
}

/**
 * Human-readable ket: "0.71|00⟩ + 0.71|11⟩", non-zero phases rendered as
 * "0.71·e^(i·90°)|1⟩". Basis labels in display order (rightmost = qubit 0).
 */
export function ketString(s: StateVector): string {
  const terms: string[] = [];
  for (let i = 0; i < s.amps.length; i++) {
    const { mag, phaseDeg } = ampDisplay(s.amps[i]);
    if (mag < 5e-3) continue; // would render as "0.00"
    const bits = i.toString(2).padStart(s.nQubits, "0");
    const deg = Math.round(phaseDeg) % 360;
    const phase = deg === 0 ? "" : `·e^(i·${deg}°)`;
    terms.push(`${mag.toFixed(2)}${phase}|${bits}⟩`);
  }
  return terms.length > 0 ? terms.join(" + ") : "0";
}
