/**
 * Engine tests — two layers (EXPLAINER-DESIGN.md §4):
 *
 * 1. ORACLE: every circuit in fixtures/oracle.json (generated by
 *    fixtures/generate_fixtures.py from quantum-linux/emulator/qcpu.py)
 *    must match the TS engine amplitude-for-amplitude to 1e-9. Both
 *    engines apply identical matrices in identical order under the same
 *    little-endian convention, so agreement is exact — a global-phase-only
 *    mismatch would mean a convention bug, not a tolerance issue.
 *
 * 2. PURE-TS: reducedBloch sign/length pins, concurrence, mulberry32
 *    determinism, measurement collapse + seeded distribution bounds.
 */

import { describe, expect, it } from "vitest";

import {
  GATES1,
  type StateVector,
  ampDisplay,
  applyCNOT,
  applyCZ,
  applyGate1,
  concurrence,
  ketString,
  measureAll,
  measureQubit,
  mulberry32,
  probOfQubit,
  probabilities,
  reducedBloch,
  zero,
} from "./engine";
import oracle from "./fixtures/oracle.json";

const ORACLE_TOL = 1e-9;

/** Op-token grammar shared with generate_fixtures.py. */
function runOps(nQubits: number, ops: string[]): StateVector {
  let s = zero(nQubits);
  for (const op of ops) {
    const m1 = /^(H|X|Y|Z|S|T)(\d)$/.exec(op);
    if (m1) {
      s = applyGate1(s, GATES1[m1[1] as keyof typeof GATES1], Number(m1[2]));
      continue;
    }
    const m2 = /^(CNOT|CZ)(\d)(\d)$/.exec(op);
    if (m2) {
      const [a, b] = [Number(m2[2]), Number(m2[3])];
      s = m2[1] === "CNOT" ? applyCNOT(s, a, b) : applyCZ(s, a, b);
      continue;
    }
    throw new Error(`unknown op token: ${op}`);
  }
  return s;
}

/** Convenience circuit builders used across the pure-TS tests. */
const hState = () => applyGate1(zero(1), GATES1.H, 0); // (|0⟩+|1⟩)/√2
const bell = () => applyCNOT(applyGate1(zero(2), GATES1.H, 0), 0, 1); // (|00⟩+|11⟩)/√2
const product = () => applyGate1(zero(2), GATES1.H, 0); // (|00⟩+|01⟩)/√2

describe("oracle: TS engine matches qcpu.py amplitudes (1e-9, no phase normalization)", () => {
  it("covers all 11 contract circuits", () => {
    expect(oracle.length).toBe(11);
  });

  for (const circuit of oracle) {
    it(circuit.name, () => {
      const s = runOps(circuit.nQubits, circuit.ops);
      expect(s.amps.length).toBe(circuit.amps.length);
      for (let i = 0; i < circuit.amps.length; i++) {
        const [re, im] = circuit.amps[i];
        expect(
          Math.abs(s.amps[i].re - re),
          `amps[${i}].re of ${circuit.name}`,
        ).toBeLessThan(ORACLE_TOL);
        expect(
          Math.abs(s.amps[i].im - im),
          `amps[${i}].im of ${circuit.name}`,
        ).toBeLessThan(ORACLE_TOL);
      }
    });
  }
});

describe("reducedBloch (behavioral pins from EXPLAINER-DESIGN §3)", () => {
  it("zero(1) → z=+1, r=1", () => {
    const b = reducedBloch(zero(1), 0);
    expect(b.z).toBeCloseTo(1, 12);
    expect(b.x).toBeCloseTo(0, 12);
    expect(b.y).toBeCloseTo(0, 12);
    expect(b.r).toBeCloseTo(1, 12);
  });

  it("H|0⟩ → x=+1, r≈1", () => {
    const b = reducedBloch(hState(), 0);
    expect(b.x).toBeCloseTo(1, 12);
    expect(b.y).toBeCloseTo(0, 12);
    expect(b.z).toBeCloseTo(0, 12);
    expect(b.r).toBeCloseTo(1, 12);
  });

  it("S·H|0⟩ → y=+1, r≈1", () => {
    const b = reducedBloch(applyGate1(hState(), GATES1.S, 0), 0);
    expect(b.y).toBeCloseTo(1, 12);
    expect(b.x).toBeCloseTo(0, 12);
    expect(b.z).toBeCloseTo(0, 12);
    expect(b.r).toBeCloseTo(1, 12);
  });

  it("Bell (|00⟩+|11⟩)/√2 → r≈0 for both qubits (the sphere's breakdown IS the lesson)", () => {
    const s = bell();
    expect(reducedBloch(s, 0).r).toBeCloseTo(0, 12);
    expect(reducedBloch(s, 1).r).toBeCloseTo(0, 12);
  });

  it("product (|00⟩+|01⟩)/√2 → r≈1 for both qubits", () => {
    const s = product();
    expect(reducedBloch(s, 0).r).toBeCloseTo(1, 12);
    expect(reducedBloch(s, 1).r).toBeCloseTo(1, 12);
  });
});

describe("concurrence (2-qubit pure states)", () => {
  it("Bell state → 1", () => {
    expect(concurrence(bell())).toBeCloseTo(1, 12);
  });

  it("factorable superposition (|00⟩+|01⟩)/√2 → 0 (superposition ≠ entanglement)", () => {
    expect(concurrence(product())).toBeCloseTo(0, 12);
  });

  it("|00⟩ → 0", () => {
    expect(concurrence(zero(2))).toBeCloseTo(0, 12);
  });

  it("throws for nQubits ≠ 2", () => {
    expect(() => concurrence(zero(1))).toThrow(RangeError);
    expect(() => concurrence(zero(3))).toThrow(RangeError);
  });
});

describe("mulberry32", () => {
  it("is deterministic: same seed → identical sequence", () => {
    const a = mulberry32(0x5eed);
    const b = mulberry32(0x5eed);
    for (let i = 0; i < 100; i++) {
      expect(a()).toBe(b());
    }
  });

  it("different seeds diverge and all values lie in [0, 1)", () => {
    const a = mulberry32(1);
    const b = mulberry32(2);
    const aSeq = Array.from({ length: 10 }, a);
    const bSeq = Array.from({ length: 10 }, b);
    expect(aSeq).not.toEqual(bSeq);
    for (const v of [...aSeq, ...bSeq]) {
      expect(v).toBeGreaterThanOrEqual(0);
      expect(v).toBeLessThan(1);
    }
  });
});

describe("measureQubit — the only collapse", () => {
  it("collapsed state is renormalized and repeat measurement is deterministic", () => {
    const rand = mulberry32(0x5eed);
    for (let trial = 0; trial < 20; trial++) {
      const { outcome, collapsed } = measureQubit(hState(), 0, rand);
      const total = probabilities(collapsed).reduce((acc, p) => acc + p, 0);
      expect(total).toBeCloseTo(1, 12);
      const marginal = probOfQubit(collapsed, 0);
      expect(outcome === 1 ? marginal.p1 : marginal.p0).toBeCloseTo(1, 12);
      // Measuring the same qubit again returns the same answer, always.
      const again = measureQubit(collapsed, 0, rand);
      expect(again.outcome).toBe(outcome);
    }
  });

  it("measuring one half of a Bell pair collapses the other half to the same bit", () => {
    const rand = mulberry32(42);
    let saw0 = false;
    let saw1 = false;
    for (let trial = 0; trial < 50; trial++) {
      const { outcome, collapsed } = measureQubit(bell(), 0, rand);
      const other = probOfQubit(collapsed, 1);
      expect(outcome === 1 ? other.p1 : other.p0).toBeCloseTo(1, 12);
      if (outcome === 0) saw0 = true;
      else saw1 = true;
    }
    expect(saw0 && saw1).toBe(true); // both branches exercised
  });

  it("seeded 1000-shot distribution on H|0⟩ is 50% ± 5% (chi-square-loose)", () => {
    const rand = mulberry32(0x5eed);
    let ones = 0;
    for (let shot = 0; shot < 1000; shot++) {
      ones += measureQubit(hState(), 0, rand).outcome;
    }
    expect(ones).toBeGreaterThanOrEqual(450);
    expect(ones).toBeLessThanOrEqual(550);
  });
});

describe("measureAll", () => {
  it("on a Bell pair returns only correlated outcomes 00 / 11", () => {
    const rand = mulberry32(7);
    for (let trial = 0; trial < 50; trial++) {
      const { outcome, bits, collapsed } = measureAll(bell(), rand);
      expect([0, 3]).toContain(outcome);
      expect(bits).toBe(outcome === 0 ? "00" : "11");
      expect(probabilities(collapsed)[outcome]).toBeCloseTo(1, 12);
    }
  });

  it("bits string is display order |q1 q0⟩ — rightmost character is qubit 0", () => {
    const rand = mulberry32(1);
    const s = applyGate1(zero(2), GATES1.X, 0); // |01⟩, qubit0 = 1
    const { outcome, bits } = measureAll(s, rand);
    expect(outcome).toBe(1);
    expect(bits).toBe("01");
  });
});

describe("applyCZ", () => {
  it("flips the sign of |11⟩ only and is symmetric in its arguments", () => {
    const s11 = applyGate1(applyGate1(zero(2), GATES1.X, 0), GATES1.X, 1);
    const a = applyCZ(s11, 0, 1);
    const b = applyCZ(s11, 1, 0);
    expect(a.amps[3].re).toBeCloseTo(-1, 12);
    expect(b.amps[3].re).toBeCloseTo(-1, 12);
    const untouched = applyCZ(zero(2), 0, 1);
    expect(untouched.amps[0].re).toBeCloseTo(1, 12);
  });
});

describe("display helpers", () => {
  it("ampDisplay: phaseDeg ∈ [0, 360)", () => {
    expect(ampDisplay({ re: 1, im: 0 })).toEqual({ mag: 1, phaseDeg: 0 });
    expect(ampDisplay({ re: 0, im: 1 }).phaseDeg).toBeCloseTo(90, 9);
    expect(ampDisplay({ re: -1, im: 0 }).phaseDeg).toBeCloseTo(180, 9);
    expect(ampDisplay({ re: 0, im: -1 }).phaseDeg).toBeCloseTo(270, 9);
    expect(ampDisplay({ re: 0, im: 0 })).toEqual({ mag: 0, phaseDeg: 0 });
  });

  it("ketString renders magnitude, phase and display-order labels", () => {
    expect(ketString(hState())).toBe("0.71|0⟩ + 0.71|1⟩");
    expect(ketString(applyGate1(hState(), GATES1.S, 0))).toBe(
      "0.71|0⟩ + 0.71·e^(i·90°)|1⟩",
    );
    expect(ketString(bell())).toBe("0.71|00⟩ + 0.71|11⟩");
    expect(ketString(applyGate1(zero(2), GATES1.X, 0))).toBe("1.00|01⟩");
    // H,Z,H interference: the |0⟩ amplitude cancels to ~1e-16 and is hidden.
    const interfered = applyGate1(
      applyGate1(hState(), GATES1.Z, 0),
      GATES1.H,
      0,
    );
    expect(ketString(interfered)).toBe("1.00|1⟩");
  });
});

describe("input validation", () => {
  it("rejects out-of-range targets and duplicate 2-qubit operands", () => {
    expect(() => applyGate1(zero(1), GATES1.H, 1)).toThrow(RangeError);
    expect(() => applyGate1(zero(1), GATES1.H, -1)).toThrow(RangeError);
    expect(() => applyCNOT(zero(2), 0, 0)).toThrow(RangeError);
    expect(() => applyCZ(zero(2), 1, 1)).toThrow(RangeError);
    expect(() => zero(0)).toThrow(RangeError);
  });
});
